import { Alignment } from "./alignment";
import { Monster } from "./monster.svelte";
import { Range } from "./range";

export const MONSTERS: Record<string, Monster> = {
	PsKetyCZRs: new Monster({
		id: "PsKetyCZRs",
		image: "assets/monster-rat.png",
		name: "Rat",
		description: "A clever dog sizes rat with red piercing eyes",
		level: 0,
		alignment: Alignment.NEUTRAL,
		movement: Range.NEAR,
		maxHitPoints: 1,
		hitPoints: 1,
		armorClass: 9,
		attacks: ["1 bite (near) +0 (1 + disease)"],
		stats: {
			strength: 4,
			dexterity: 14,
			constitution: 10,
			intelligence: 10,
			wisdom: 10,
			charisma: 1,
		},
	}),
	kNW5WT48qb: new Monster({
		id: "kNW5WT48qb",
		image: "assets/monster-skeleton.png",
		name: "Skeleton Warrior",
		description: "A skeleton in leather armor bearing rusty sword or axe.",
		level: 1,
		alignment: Alignment.CHAOTIC,
		movement: Range.NEAR,
		maxHitPoints: 5,
		hitPoints: 5,
		armorClass: 11,
		attacks: ["1 sword +1 (near) (1d10)"],
		stats: {
			strength: 12,
			dexterity: 10,
			constitution: 14,
			intelligence: 6,
			wisdom: 10,
			charisma: 8,
		},
	}),
	SXD0djMVAa: new Monster({
		id: "SXD0djMVAa",
		image: "assets/monster-skeleton-archer.png",
		name: "Skeleton Archer",
		description: "A skeleton in leather armor bearing a shortbow",
		level: 1,
		alignment: Alignment.CHAOTIC,
		movement: Range.NEAR,
		maxHitPoints: 5,
		hitPoints: 5,
		armorClass: 11,
		attacks: ["1 shortbow (far) +1 (1d4)"],
		stats: {
			strength: 12,
			dexterity: 10,
			constitution: 14,
			intelligence: 6,
			wisdom: 10,
			charisma: 8,
		},
	}),
	HdPWI7rYT2: new Monster({
		id: "HdPWI7rYT2",
		image: "assets/monster-giant-rat.png",
		name: "Giant Rat",
		description: "A clever dog sizes rat with red piercing eyes",
		level: 1,
		alignment: Alignment.NEUTRAL,
		movement: Range.NEAR,
		maxHitPoints: 5,
		hitPoints: 5,
		armorClass: 10,
		attacks: ["1 bite (near) +1 (1d4 + disease)"],
		stats: {
			strength: 6,
			dexterity: 14,
			constitution: 12,
			intelligence: 10,
			wisdom: 10,
			charisma: 1,
		},
	}),
	q1joogSPXJ: new Monster({
		id: "q1joogSPXJ",
		image: "assets/monster-ogre.png",
		name: "Ogre",
		description: "A huge tusked hunk of dumb muscle and anger",
		level: 5,
		alignment: Alignment.CHAOTIC,
		movement: Range.NEAR,
		maxHitPoints: 24,
		hitPoints: 24,
		armorClass: 9,
		attacks: ["2 greatclub +5 (near) (2d6)", "1 stomp +5 (near) (2d8)"],
		stats: {
			strength: 18,
			dexterity: 6,
			constitution: 16,
			intelligence: 6,
			wisdom: 4,
			charisma: 6,
		},
	}),
};
